### SENSOR MAINTENANCE DATA EXPLORATION & QUALITY ASSESSMENT USING PYTHON

In [ ]:
#Loading data and importing pandas library

import pandas as pd

# path = r'# put your file path here'

#### Understanding the data

In [3]:
# How many columns and rows are there
(
    pd.read_csv(path)
    .head()
    )

,Sensor_ID,Timestamp,Voltage (V),Current (A),Temperature (°C),Power (W),Humidity (%),Vibration (m/s²),Equipment_ID,Operational Status,...,Ambient Temperature (°C),Ambient Humidity (%),External Factors,X,Y,Z,Equipment Relationship,Equipment Criticality,Fault Detected,Predictive Maintenance Trigger
0,S_1,2024-01-01 00:00:00,110,0.5,20,55.0,40,0.20,E_1,Operational,...,20,40,Clear Weather,0,0,0,Independent,High,1,1
1,S_2,2024-01-01 01:00:00,111,0.6,21,66.6,41,0.25,E_2,Under Maintenance,...,21,41,Storm,1,1,1,Dependent,Medium,0,0
2,S_3,2024-01-01 02:00:00,112,0.7,22,78.4,42,0.30,E_3,Operational,...,22,42,Clear Weather,2,2,2,Dependent,High,0,0
3,S_4,2024-01-01 03:00:00,113,0.8,23,90.4,43,0.35,E_4,Under Maintenance,...,23,43,Storm,3,3,3,Independent,Medium,1,0
4,S_5,2024-01-01 04:00:00,114,0.9,24,102.6,44,0.40,E_5,Operational,...,24,44,Clear Weather,4,4,4,Dependent,High,0,1

In [4]:
# How many columns and rows are in the data: 500 observations, and 27 feaatures
(
    pd.read_csv(path)
    .shape
    )

(500, 27)

In [5]:
# Inspecting the structure.

(
    pd.read_csv(path)
    .info()
    )

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Sensor_ID                       500 non-null    str
 1   Timestamp                       500 non-null    str
 2   Voltage (V)                     500 non-null    int64
 3   Current (A)                     500 non-null    float64
 4   Temperature (°C)                500 non-null    int64
 5   Power (W)                       500 non-null    float64
 6   Humidity (%)                    500 non-null    int64
 7   Vibration (m/s²)                500 non-null    float64
 8   Equipment_ID                    500 non-null    str
 9   Operational Status              500 non-null    str
 10  Fault Status                    500 non-null    str
 11  Failure Type                    200 non-null    str
 12  Last Maintenance Date           500 non-null    str
 13  Maintenance Type                500 non-null    str
 14  Failure History                 500 non-null    str
 15  Repair Time (hrs)               500 non-null    int64
 16  Maintenance Costs (USD)         500 non-null    int64
 17  Ambient Temperature (°C)        500 non-null    int64
 18  Ambient Humidity (%)            500 non-null    int64
 19  External Factors                500 non-null    str
 20  X                               500 non-null    int64
 21  Y                               500 non-null    int64
 22  Z                               500 non-null    int64
 23  Equipment Relationship          500 non-null    str
 24  Equipment Criticality           500 non-null    str
 25  Fault Detected                  500 non-null    int64
 26  Predictive Maintenance Trigger  500 non-null    int64
dtypes: float64(3), int64(12), str(12)
memory usage: 105.6 KB

##### The data sets contains 500 records and 27 features. Maintenance date is wrongly stored as strings instead of date.  The numericaal variables include Voltage (V)','Current (A)','Temperature (°C)', 'Power (W)', 'Humidity (%)', 'Vibration (m/s²)', 'Repair Time (hrs)', 'Maintenance Costs (USD)', 'Ambient Temperature (°C)', 'Ambient Humidity (%)', 'X', 'Y', 'Z', 'Fault Detected', and 'Predictive Maintenance Trigger'

In [6]:
# Checking for null values
(
    pd.read_csv(path)
    .isnull()
    .sum()
    
    )
#There are 300 missing value in "Failure Type" column while other have none

Sensor_ID                           0
Timestamp                           0
Voltage (V)                         0
Current (A)                         0
Temperature (°C)                    0
Power (W)                           0
Humidity (%)                        0
Vibration (m/s²)                    0
Equipment_ID                        0
Operational Status                  0
Fault Status                        0
Failure Type                      300
Last Maintenance Date               0
Maintenance Type                    0
Failure History                     0
Repair Time (hrs)                   0
Maintenance Costs (USD)             0
Ambient Temperature (°C)            0
Ambient Humidity (%)                0
External Factors                    0
X                                   0
Y                                   0
Z                                   0
Equipment Relationship              0
Equipment Criticality               0
Fault Detected                      0
Predictive Maintenance Trigger      0
dtype: int64

In [7]:
(
    pd.read_csv(path)
    .columns
    .tolist()
    )

['Sensor_ID',
 'Timestamp',
 'Voltage (V)',
 'Current (A)',
 'Temperature (°C)',
 'Power (W)',
 'Humidity (%)',
 'Vibration (m/s²)',
 'Equipment_ID',
 'Operational Status',
 'Fault Status',
 'Failure Type',
 'Last Maintenance Date',
 'Maintenance Type',
 'Failure History',
 'Repair Time (hrs)',
 'Maintenance Costs (USD)',
 'Ambient Temperature (°C)',
 'Ambient Humidity (%)',
 'External Factors',
 'X',
 'Y',
 'Z',
 'Equipment Relationship',
 'Equipment Criticality',
 'Fault Detected',
 'Predictive Maintenance Trigger']

In [8]:
(
    pd.read_csv(path)
    .describe()
    )
# Average maintenance cost is $195 and average repair time is about 2.3 hrs

,Voltage (V),Current (A),Temperature (°C),Power (W),Humidity (%),Vibration (m/s²),Repair Time (hrs),Maintenance Costs (USD),Ambient Temperature (°C),Ambient Humidity (%),X,Y,Z,Fault Detected,Predictive Maintenance Trigger
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.00000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,114.500000,0.700000,24.500000,80.350000,44.500000,0.300000,2.336000,195.000000,22.00000,42.00000,49.500000,24.500000,14.30000,0.334000,0.250000
std,2.875158,0.141563,2.875158,17.293311,2.875158,0.070781,3.402095,28.751579,1.41563,1.41563,28.894979,14.445322,8.62315,0.472112,0.433446
min,110.000000,0.500000,20.000000,55.000000,40.000000,0.200000,0.000000,150.000000,20.00000,40.00000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,112.000000,0.600000,22.000000,66.600000,42.000000,0.250000,0.000000,170.000000,21.00000,41.00000,24.750000,12.000000,7.00000,0.000000,0.000000
50%,114.500000,0.700000,24.500000,80.150000,44.500000,0.300000,0.000000,195.000000,22.00000,42.00000,49.500000,24.500000,14.00000,0.000000,0.000000
75%,117.000000,0.800000,27.000000,94.400000,47.000000,0.350000,6.000000,220.000000,23.00000,43.00000,74.250000,37.000000,22.00000,1.000000,0.250000
max,119.000000,0.900000,29.000000,107.100000,49.000000,0.400000,9.000000,240.000000,24.00000,44.00000,99.000000,49.000000,29.00000,1.000000,1.000000

#####
1.  The data set contains 500 maintenance records.
2. There aare no missing values except for " Failure type" columns where there aare 300 missing values.
3.  Averge maintenance cost was $195. Average vibrations reading is 0.3 m/s2 and maximu is 0.4m/s2.
4. The maximum rpair hour is 9hrs, and average repair time is 2.3 hours.